name: Coverity scan
on:
  # coverity_daily job runs once daily at 00:30 UTC due to
  # https://scan.coverity.com/faq#frequency
  schedule:
    - cron: "30 0 * * *"
  # coverity_label job triggers if PR has 'coverity' label set.
  # This job likely cannot be re-run on the same day or we will
  # hit the build submission limit (see above link)
  pull_request_target:
    branches:
      - master
    types:
      - labeled
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverity:
    if: |
      github.event_name == 'schedule' ||
      (github.event.label.name == 'coverity' && github.event_name == 'pull_request_target')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Set description
      run: |
        if [ ${{ github.event_name }} == 'pull_request_target' ]; then
          echo "DESCRIPTION=Pull Request number ${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        else
          echo "DESCRIPTION=Daily scheduled run ${{ github.ref }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Configure
      uses: ./.github/actions/configure

    - name: Execute and submit coverity scan
      uses: vapier/coverity-scan-action@v1.8.0
      with:
        email: "sssd-maint@redhat.com"
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        working-directory: x86_64
        description: ${{ env.DESCRIPTION }}
